### ISSUE TITLE
IfxPy-3.0.3-cp37-cp37m-win_amd64.whl not working

### ISSUE THREAD

**Issue by agrawama** [OpenInformix/IfxPy#20]
Hi Team,

I have installed IfxPy-3.0.3-cp37-cp37m-win_amd64.whl mentioned wheel in windows 64 bit python 7.3 but it not working as expected.

could you please update the .whl file and please publish wheels for all the python versions

Thanks in advance!!

**Comment by jsagrera** [comment]
do you have CSDK installed on that box? IfxPy needs some of the CSDK libraries and resources files to work.
you can find the IBM link in the readme page.

**Comment by agrawama** [comment]
Thanks for quick reply!!

Yes CSDK (icsdk.4.10.TC6.WIN-32) is installed in my system.

I am getting the following error :-

>>> import IfxPyDbi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AmanAgrawal\AppData\Local\Programs\Python\Python37\lib\site-packages\IfxPyDbi.py", line 85, in <module>
    import IfxPy
ImportError: DLL load failed: The specified module could not be found.

**Comment by deokershesh** [comment]
Please make sure INFORMIXDIR environment variable is set to CSDK install
location and also PATH has $INFORMIXDIR/bin.

**Comment by jsagrera** [comment]
By reading the stackoverflow post, I got the idea that you were using the 64-bit of Python/IfxPy.
That means you need a 64-bit CSDK. The prefix on the version indicates the architecture. TC6 is 32-bit, FC6 is 64.

If your Python is 64, try installing a 64-BIT CSDK.

**Comment by agrawama** [comment]
I have tried with both 32 bit and 64 bit CSDK still same error persist.

**Comment by jsagrera** [comment]
If you get "ImportError: DLL load failed: The specified module could not be found." is because, either the IfxPy DLL can be loaded or one of its dependencies can't be loaded. 
Most of the time this happens because CSDK does not match the architecture of the Python module, or the libraries are not in the path.
First thing you should check is if the ODBC works at all. From the same session you are using to build/install the IfxPy module, try to run "odbcad32" (Windows odbc administrator tool) and create a DSN  pointing to you Informix server. If you can connect from that CMD, it means the environment (PATH/INFORMIXDIR) is valid, and any other program (e.g. Python+IfxPy) should be able to use the driver (find the dlls).

**Comment by Amrouane** [comment]
@agrawama Did you fix the problem?

**Comment by agrawama** [comment]
@Amrouane yes I am able to use ifxpy successfully.

Please fine the stackoverflow link

https://stackoverflow.com/questions/57121703/not-able-to-install-ifxpy-package-using-pip3-install-on-windows

https://stackoverflow.com/questions/57143697/how-to-install-ifxpy-module-in-docker-image-python3-6
