### ISSUE TITLE
IfxPy import issue in Thonny IDE

### ISSUE THREAD

**Issue by migu-el** [OpenInformix/IfxPy#22]
When i try run a pyton sample in Thonny this error message is showed :

> %Run sample.py
> Traceback (most recent call last):
> File "/home/pi/pysamples/sample.py", line 1, in 
> import IfxPy
> File "/usr/lib/python3/dist-packages/thonny/backend.py", line 305, in _custom_import
> module = self._original_import(*args, **kw)
> ImportError: libifdmr.so: cannot open shared object file: No such file or directory.
 
 But in console mode, the same sample python file run fine...
 
> pi@raspberrypi:~/pysamples $ python3 sample.py
> -- Record 1 --1-BOYS 4/5, 6/7, 8, 10/12, 14/16, 18, 20
> -- Record 2 --2-BOYS XS, S, M, L, XL, 2XL, 3XL
> -- Record 3 --3-BOYS XS(4-5), S(6-7), M(8), L(10-12), XL(14-16, XXL(18), 10/12H, 14/16H
> -- Record 4 --4-GIRLS 4/5, 6/6X, 7/8, 10/12, 14/16
> -- Record 5 --5-GIRLS 4, 5, 6, 7, 8, 10, 12, 14

I am using Os Rasbian buster + Python 3x + IfxPy database Driver.

The libifdmr.so is located in {INFORMIXDIR}/lib/cli (this is the env) :

> SHELL=/bin/bash
> COLORTERM=truecolor
> XDG_CONFIG_DIRS=/etc/xdg
> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
> XDG_MENU_PREFIX=lxde-pi-
> INFORMIXDIR=/opt/ibm/informix
> LANGUAGE=en_US.UTF-8
> _LXSESSION_PID=512
> SSH_AUTH_SOCK=/tmp/ssh-YqELtJu2PGgK/agent.512
> XDG_CONFIG_HOME=/home/pi/.config
> DESKTOP_SESSION=LXDE-pi
> SSH_AGENT_PID=554
> NO_AT_BRIDGE=1
> XDG_SEAT=seat0
> PWD=/opt/ibm/informix/lib/cli
> LOGNAME=pi
> XDG_SESSION_DESKTOP=lightdm-xsession
> QT_QPA_PLATFORMTHEME=qt5ct
> XDG_SESSION_TYPE=x11
> GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
> XAUTHORITY=/home/pi/.Xauthority
> XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/pi
> HOME=/home/pi
> LANG=en_US.UTF-8
> LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
> XDG_CURRENT_DESKTOP=LXDE
> VTE_VERSION=5402
> XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
> ODBCINI=/etc/odbc.ini
> XDG_SESSION_CLASS=user
> TERM=xterm-256color
> USER=pi
> DISPLAY=:0.0
> SHLVL=1
> XDG_VTNR=7
> XDG_SESSION_ID=c1
> LD_LIBRARY_PATH=/opt/ibm/informix/lib:/opt/ibm/informix/lib/cli:/opt/ibm/informix/lib/esql:
> XDG_RUNTIME_DIR=/run/user/1000
> LC_ALL=en_US.UTF-8
> XDG_DATA_DIRS=/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg
> PATH=/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/opt/ibm/informix/bin
> GDMSESSION=lightdm-xsession
> SAL_USE_VCLPLUGIN=gtk3
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> TEXTDOMAIN=Linux-PAM
> _=/usr/bin/env
> OLDPWD=/opt/ibm/informix/lib
> 
Any ideas to solve this issue in Thonny?, 

Your help is great appreciated!!!!

**Comment by jsagrera** [comment]
I guess Thonny is not inhering LD_LIBRARY_PATH value, and that's why the Informix CLI libraries are not been loaded.  Try adding the informix lib directories to you system, something like:

```
informix@irk:/data/informix/IBM/14.10.FC1$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

informix@irk:/data/informix/IBM/14.10.FC1$ ls -la /etc/ld.so.conf.d/
total 48
drwxr-xr-x   2 root root  4096 Aug 22 11:09 .
drwxr-xr-x 154 root root 12288 Aug 21 06:58 ..
-rw-r--r--   1 root root    39 Mar  6 15:02 egm.conf
-rw-r--r--   1 root root   108 Jan 15  2018 i386-linux-gnu.conf
-rw-r--r--   1 root root   108 Aug 22 11:09 ifx.conf
-rw-r--r--   1 root root    44 Jan 27  2016 libc.conf
-rw-r--r--   1 root root   276 Nov  5  2018 vmware-tools-libraries.conf
-rw-r--r--   1 root root    68 Apr 15  2016 x86_64-linux-gnu.conf
-rw-r--r--   1 root root    56 Jan 15  2018 zz_i386-biarch-compat.conf
-rw-r--r--   1 root root    58 Jan 15  2018 zz_x32-biarch-compat.conf

informix@irk:/data/informix/IBM/14.10.FC1$ cat /etc/ld.so.conf.d/ifx.conf 
/data/informix/IBM/4.10.FC13/lib
/data/informix/IBM/4.10.FC13/lib/esql
/data/informix/IBM/4.10.FC13/lib/cli
informix@irk:/data/informix/IBM/14.10.FC1$ 

```
"/data/informix/IBM/4.10.FC13" if my $INFORMIXDIR

Another option would be find where env variables are set in Thonny and add LD_LIBRARY_PATH.

**Comment by aicatalysts** [comment]
@jsagrera - thanks for this!  

Note to others: don't forget to run "ldconfig" after making these changes.
