### ISSUE TITLE
Error 404: not found from dependency https://hcl-onedb.github.io/odbc/Unknown on macos

### ISSUE THREAD

**Issue by tourdownunder** [OpenInformix/IfxPy#54]
```sh
(venv-38) bash-3.2$ pip install IfxPy
Looking in indexes: http://localhost:3141/root/pypi/+simple/
Collecting IfxPy
  Downloading http://localhost:3141/root/pypi/%2Bf/788/4365e04dd2a00/IfxPy-3.0.5.tar.gz (155 kB)
     |████████████████████████████████| 155 kB 51.4 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/david/.local/share/virtualenvs/analytics-ingest-platform-ey8Fc8jM/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f1/0jzpddz54_7fr79d9szr58s80000gn/T/pip-install-yf55_wyn/ifxpy/setup.py'"'"'; __file__='"'"'/private/var/folders/f1/0jzpddz54_7fr79d9szr58s80000gn/T/pip-install-yf55_wyn/ifxpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/f1/0jzpddz54_7fr79d9szr58s80000gn/T/pip-pip-egg-info-4_3pganc
         cwd: /private/var/folders/f1/0jzpddz54_7fr79d9szr58s80000gn/T/pip-install-yf55_wyn/ifxpy/
    Complete output (19 lines):
    Detected 64-bit Python
    Downloading : https://hcl-onedb.github.io/odbc/Unknown
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f1/0jzpddz54_7fr79d9szr58s80000gn/T/pip-install-yf55_wyn/ifxpy/setup.py", line 98, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv-38) bash-3.2$ 
````

**Comment by deokershesh** [comment]
Is this on Linux? Could you send output of "uname -a"?

**Comment by tourdownunder** [comment]
It is MacOS Catalina

```sh
(venv-38) bash-3.2$ uname -a
Darwin Davids-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by deokershesh** [comment]
Did you set value of INFORMIXDIR before installing Python driver?

I think Informix CSDK is not supported on oMacOS on latest version i.e.
CSDK 4.50.X

**Comment by tourdownunder** [comment]
Thanks. It does mention OS X on their [downloads page](https://www.ibm.com/support/pages/informix-client-software-development-kit-client-sdk-and-informix-connect-system-requirements)

I'm happy for this to be closed if there is nothing that can be done. I develop on Macos and deploy to linux through docker so its not too unworkable.

**Comment by deokershesh** [comment]
CSDK 4.10 (Not latest 4.50) version is available on MacOS. Please install
the CSDK 4.10, set the INFORMIXDIR value to installed location and try to
install Python driver.

**Comment by tourdownunder** [comment]
I wasted way too much time today trying to navigate the downloads page without avail. Should I have created a account would things magically appear?

**Comment by tourdownunder** [comment]
As per issue #11 this can be closed.

**Comment by deokershesh** [comment]
Hi David,
Yes, you have to create IBM id to download the CSDK package.
