### ISSUE TITLE
Closing the connection to non logged data base fails

### ISSUE THREAD

**Issue by TomBr130** [OpenInformix/IfxPy#56]
Hi everyone, 

I am new to IfxPy and Informix and have an issue or rather a question concerning using IfxPy with non logged databases. I was trying to connect using IfxPy to this non logged Informix database via an ODBC driver. 

`import IfxPyDbi as dbapi2

source_connection = dbapi2.connect(conn_string, "", "")
source_connection.close()  `

Everything works fine until I want to close the connection again. Then I get this error:

`  File "path\lib\site-packages\IfxPyDbi.py", line 557, in close
    return_value = IfxPy.close(self.conn_handler)
Exception: [Informix][Informix ODBC Driver]Driver not capable. SQLCODE=-11092

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extractor_main.py", line 23, in <module>
    Test_data_base_connection.test(dataload_configuration)
  File "some_other_path\test_connection.py", line 47, in test
    source_connection.conn.close()  # this is the same for postgres and informix
  File "path\lib\site-packages\IfxPyDbi.py", line 559, in close
    raise _get_exception(inst)
IfxPyDbi.Error: ifx_pydb::Error: [Informix][Informix ODBC Driver]Driver not capable. SQLCODE=-11092`

This is probably to expect as the database has no transaction logging. I found this issue: https://github.com/OpenInformix/IfxPy/issues/3 with the same problem. But the proposed workaround doesn't work for me. Probably because I am trying a different command. 

Is there any possibility to properly close the connection to a non logged Informix database using IfxPy? Or is there a guide for how to deal with non logged data bases? Unfortunately, the admins of this database won't change the logging.

Thanks a lot!
Tom

**Comment by whitemice** [comment]
Experiencing the same issue disconnection from a non-logged database
