### ISSUE TITLE
How to bind binary data as a parameter

### ISSUE THREAD

**Issue by cypres-it** [OpenInformix/IfxPy#6]
I tried several ways to get binary data into a column of type BLOB:

The following code leads to a `Segmentation fault`:
```python
import IfxPy
conn = IfxPy.connect(...)
IfxPy.exec_immediate(conn, "drop table if exists t1")
IfxPy.exec_immediate(conn, "create table t1 (c1 blob)")
IfxPy.exec_immediate(conn, "insert into t1 (c1) values (?)", ("...",))
```

My second attempt:
```python
import IfxPy
conn=IfxPy.connect(...)
IfxPy.exec_immediate(conn, "drop table if exists t1")
IfxPy.exec_immediate(conn, "create table t1 (c1 blob)")
stmt = IfxPy.prepare(conn, "insert into t1 (c1) values (?)")
param_type = IfxPy.PARAM_FILE
#param_type = IfxPy.SQL_PARAM_INPUT
rc = IfxPy.bind_param(stmt, 1, "/var/tmp/pic1.jpg", param_type, IfxPy.SQL_BINARY)
print rc
rc = IfxPy.execute(stmt)
print rc
```
This leads to:
 ```
True

 Error: SQLBindFileToParam not supported yet
 Binding a parameter marker in an SQL statement to a file reference will be a new featureTraceback (most recent call last):
  File "testBinary2.py", line 15, in <module>
    rc = IfxPy.execute(stmt)
Exception: Binding Error 3:
 ```

If I set `param_type` to `IfxPy.SQL_PARAM_INPUT` instead the result is:
```python
True
Traceback (most recent call last):
  File "testBinary2.py", line 15, in <module>
    rc = IfxPy.execute(stmt)
Exception: Statement Execute Failed: [Informix][Informix ODBC Driver][Informix]Smart-large-object error. SQLCODE=-9810
```

Is there any supported way at the moment to bind binary data to a statement?

**Comment by jsagrera** [comment]
For BLOB (binary data) use SQL_PARAM_INPUT and SQL_LONGVARBINARY:

```

d:\infx\OpenInformix\IfxPy>cat testblob.py
import os
import IfxPy

def dump(obj):
  for attr in dir(obj):
    print("obj.%s = %r" % (attr, getattr(obj, attr)))

ConStr = "SERVER=ids1210;DATABASE=stores7;"

# netstat -a | findstr  9088
conn = IfxPy.connect( ConStr, "", "")

# Drop the emp_photo table, in case it exists
drop = 'DROP TABLE emp_photo'
try:
  result = IfxPy.exec_immediate(conn, drop)
except:
  pass
# Create the emp_photo table
create = 'CREATE TABLE emp_photo (empno CHAR(6) NOT NULL, photo_format VARCHAR(10) NOT NULL, picture BLOB, PRIMARY KEY(empno, photo_format))'
try:
  result = IfxPy.exec_immediate(conn, create)
except:
  pass
# Populate the emp_photo table
emp_photo = (\
      ('000130', 'jpg', 'pic1.jpg'),\
      ('000131', 'jpg', 'pic2.jpg'),\
)

insert = 'INSERT INTO emp_photo (empno, photo_format, picture) VALUES (?, ?, ?)'
stmt = IfxPy.prepare(conn, insert)
if stmt:

  print ("INSERT BLOB")
  for photo in emp_photo:
    empno = photo[0]
    photo_format = photo[1]
    fileHandler = open(os.path.dirname(os.path.abspath(__file__)) + '/' + photo[2], 'rb')
    picture = fileHandler.read()
    IfxPy.bind_param(stmt, 1, empno, IfxPy.SQL_PARAM_INPUT)
    IfxPy.bind_param(stmt, 2, photo_format, IfxPy.SQL_PARAM_INPUT)
    IfxPy.bind_param(stmt, 3, picture, IfxPy.SQL_PARAM_INPUT,IfxPy.SQL_LONGVARBINARY)
    result = IfxPy.execute(stmt)

  print("SELECT BLOB")
  result = IfxPy.exec_immediate(conn, "select * from emp_photo")
  row=IfxPy.fetch_row(result)
  while row != False:
    fileout=IfxPy.result(result, 0) + "_out.jpg"
    print("output file: " + fileout)
    fp = open(fileout , 'wb')
    picture=IfxPy.result(result, 2)
    fp.write(picture)
    fp.close()
    row = IfxPy.fetch_row(result)

print ("DONE")

d:\infx\OpenInformix\IfxPy>dir *.jpg
 Volume in drive D is Data750
 Volume Serial Number is 13B7-1346

 Directory of d:\infx\OpenInformix\IfxPy\IfxPy

16/10/2017  09:50             4,461 pic1.jpg
16/10/2017  09:50             3,070 pic2.jpg
               2 File(s)          7,531 bytes
               0 Dir(s)  172,445,601,792 bytes free

d:\infx\OpenInformix\IfxPy>python testblob.py
INSERT BLOB
SELECT BLOB
output file: 000130_out.jpg
output file: 000131_out.jpg
DONE

d:\infx\OpenInformix\IfxPy>dir *.jpg
 Volume in drive D is Data750
 Volume Serial Number is 13B7-1346

 Directory of d:\infx\OpenInformix\IfxPy

08/08/2018  09:26             4,461 000130_out.jpg
08/08/2018  09:26             3,070 000131_out.jpg
16/10/2017  09:50             4,461 pic1.jpg
16/10/2017  09:50             3,070 pic2.jpg
               4 File(s)         15,062 bytes
               0 Dir(s)  172,445,589,504 bytes free

d:\infx\OpenInformix\IfxPy>
```

**Comment by cypres-it** [comment]
Thanks jsagrera, that works.

**Comment by jsagrera** [comment]
Glad it works.
There are some simple examples of basic use in the '.../IfxPy/tests' directory which can be useful to check how to do the module. Worth a check ;)

**Comment by cypres-it** [comment]
Thanks, sorry for the late response. I looked into IfxPy/tests/test_045_FetchTupleBinaryData_01.py and there it looks like you could simply do an exec_immediate without explicit bind_param calls. I tried that with a column of type "byte" but I only get
