### ISSUE TITLE
Unable to install IfxPy 3.0.5 in python 37

### ISSUE THREAD

**Issue by Farheen007** [OpenInformix/IfxPy#68]
this is the error trace I am getting while downloading that package. Can someone help me ?
`Collecting IfxPy
  Using cached IfxPy-3.0.5.tar.gz (155 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Detected 64-bit Python
      Downloading : https://hcl-onedb.github.io/odbc/Unknown
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/dg/2qg693ld1b50n2h712fbjsc00000gq/T/pip-install-ilvd77iq/ifxpy_59f19b2999634dac8b2b10c803786a35/setup.py", line 98, in <module>
          file_stream = BytesIO(request.urlopen(url).read())
        File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
          return opener.open(url, data, timeout)
        File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
          response = meth(req, response)
        File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
          'http', request, response, code, msg, hdrs)
        File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
          return self._call_chain(*args)
        File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
          result = func(*args)
        File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
`

**Comment by parthiv11** [comment]
Getting same error. 
Please give Any solution

**Comment by jsagrera** [comment]
Looking at the output, it appears the setup script is not detecting that you are running on a "linux" OS, so it does not set the proper tar file to download (`cliFileName` var):

You get:
```
    Detected 64-bit Python
    Downloading : https://hcl-onedb.github.io/odbc/Unknown
    ...
```    
It should be:
```
Collecting ifxpy
  Downloading https://files.pythonhosted.org/packages/98/d1/e4f1c5dfa2d9c34692cbac13fcf9f136d0391f7d0d7adff21b957c2a47ff/IfxPy-3.0.5.tar.gz (155kB)
    100%                           163kB 2.0MB/s 
Installing collected packages: ifxpy
  Running setup.py install for ifxpy ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oxe1arc3/ifxpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-shn8mmad-record/install-record.txt --single-version-externally-managed --compile:
    Detected 64-bit Python
    Downloading : https://hcl-onedb.github.io/odbc/OneDB-Linux64-ODBC-Driver.tar
    Extracting Linux ODBC files : https://hcl-onedb.github.io/odbc/OneDB-Linux64-ODBC-Driver.tar
    Smart Triggers are enabled.
    ....
```
Inside the setup.py we have:    
 ```   
    if('win32' in sys.platform):
        os_ = 'win'
        cliFileName = 'OneDB-Win64-ODBC-Driver.zip'
        prefix = 'build/lib.win-amd64-' + str(sys.version_info[0])+"."+str(sys.version_info[1]) + '/'
    elif ('linux' in sys.platform):
        os_ = 'linux'
        cliFileName = 'OneDB-Linux64-ODBC-Driver.tar'
        prefix = 'build/lib.linux-'+ platform.processor() + '-' + str(sys.version_info[0])+"."+str(sys.version_info[1]) + '/'
    else:
        cliFileName = 'Unknown'
 ```       
    
So I guess 3.7 in your box returns something else.
This is with 3.6 and 3.7 on an Ubuntu box:
```        
    dev@api.js2 ~]# python3
    Python 3.6.8 (default, Jan 14 2022, 11:04:20) 
    [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sys
    >>> sys.platform
    'linux'
    >>> 

    Python 3.7.11 (default, Aug 13 2022, 10:15:55)
    [GCC 9.4.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sys
    >>> sys.platform
    'linux'
    >>>    
```
I wonder what you get in yours.
Anyway, you can try to download and install Informix CSDK before running the pip install (setting both INFORMIXDIR and CSDK_HOME to your CSDK install directory)
The IfxPy setup script should detect that you already have CSDK and skip the download of the onedb driver.
Or manually download the OneDB ODBC driver before running 
```
    informix@w10:~/p/Python-3.7.11$ wget https://hcl-onedb.github.io/odbc/OneDB-Linux64-ODBC-Driver.tar
    informix@w10:~/p/Python-3.7.11$ mkdir /home/informix/cli
    informix@w10:~/p/Python-3.7.11$ tar xvf OneDB-Linux64-ODBC-Driver.tar -C /home/informix/cli
    informix@w10:~/p/Python-3.7.11$ export INFORMIXDIR=/home/informix/cli/onedb-odbc-driver
    informix@w10:~/p/Python-3.7.11$ export CSDK_HOME=$INFORMIXDIR

    informix@w10:~/p/Python-3.7.11$ pip3 install ifxPy
    Collecting ifxPy
      Using cached IfxPy-3.0.5.tar.gz (155 kB)
    Building wheels for collected packages: ifxPy
      Building wheel for ifxPy (setup.py) ... done
      Created wheel for ifxPy: filename=IfxPy-3.0.5-cp38-cp38-linux_x86_64.whl size=185599 sha256=1cb1d5edf38ca7f7c8276f421b282fc90ff98e2ec51e79fa42267183745a88c7
      Stored in directory: /home/informix/.cache/pip/wheels/ac/a1/02/c1250e64125838dfac42052504c6d19f892c069f513039876e
    Successfully built ifxPy
    Installing collected packages: ifxPy
    Successfully installed ifxPy-3.0.5
    informix@w10:~/p/Python-3.7.11$
```
